name = "moltwars-edge"
main = "src/worker.js"
compatibility_date = "2025-02-01"

[[durable_objects.bindings]]
name = "MOLT_DO"
class_name = "MoltHub"

[[migrations]]
tag = "v1"
new_classes = ["MoltHub"]

[vars]
ORIGIN_WS = "wss://server.moltwars.xyz/ws"
ORIGIN_HTTP = "https://server.moltwars.xyz"

routes = ["server.moltwars.xyz/*"]
